*! mdf_deliverables.ado — Master DO File pipeline stage 19 of 19
*! version 11.1.3   github.com/adinkhan7/master-do-file
*!
*!  build the client handover package (ADR-059, amending ADR-057; ADR-064)
*!
*!  Written only when run_deliverables = 1. At 0 this stage returns before it
*!  touches anything, so the ordinary workflow is untouched.
*!
*!  The package holds what a client needs to understand the survey and to
*!  reproduce the cleaned dataset, and nothing else:
*!
*!      08_Deliverables/                   (one dataset)
*!        01_CAPI & Questionnaire/         the form labeling used + questionnaire
*!        02_Import & Raw files/           the raw dataset, its import DO + CSV
*!        03_Processing Files/             the project's Processing DO
*!          01_Do Files/                   01_Labeling.do, 02_Translation.do
*!            _mdf/                        the runtime — a HIDDEN folder
*!          02_Translation/                the returned translation files
*!          03_Data/                       the analyst's support files
*!        04_Cleaned Data/                 the cleaned dataset
*!
*!  With several datasets the same four folders appear once per dataset, under
*!  08_Deliverables/NN_<dataset>/, each carrying that dataset alone; its
*!  returned translation files sit in 02_Translation/NN_<dataset>/. A folder
*!  with nothing to put in it is not made.
*!
*!  The runtime stays at 01_Do Files/_mdf/ because every Processing, Labeling
*!  and Translation DO since 11.1.0 recognises its package by that path. It is
*!  hidden, as the project's own _mdf/ is, so the client sees only their files.
*!  The package's copy of the Processing DO gains one marked line per dataset
*!  that loads that dataset's raw data on its own, for debugging; the project's
*!  own Processing DO is never touched.
*!
*!  It reproduces by standing on package mode in the generated files: copied
*!  anywhere, the Processing DO inside 03_Processing Files/ recognises the
*!  package around it, reads 02_Import & Raw files/ and writes the cleaned
*!  dataset to 04_Cleaned Data/. No Master, no mdf package, no project.
*!
*!  The folder is framework output and is rebuilt from scratch on every build,
*!  so nothing from an earlier build can linger in it (a superseded form would
*!  make the package ambiguous, and the package refuses to guess).

program define mdf_deliverables
    version 16
    *  A clean stop upstream (Run 1, a CAPI pause, a Ghost Run) sets this.
    *  `exit` inside an ado returns from the ado, not from Master, so every
    *  later stage has to stand down of its own accord.
    if "$mdf_halt" == "1" exit

    if "$run_deliverables" != "1" exit

    _mdf_load

    if "$ghost_run" == "1" {
        di as result _n "--- Deliverables skipped (Ghost Run: there is no data to hand over) ---"
        exit
    }

    *  mdf_keys closed the run log; the package build belongs in it too.
    cap log using "$log_file", append text name(hfc_master)

    *==============================================================================*
    *  WHICH PACKAGE THE PROCESSING DO CAN REBUILD FROM
    *==============================================================================*
    *  Only a Processing DO generated by v11 or later recognises the package
    *  layout. One still on an older template gets the v10.2.0 package, which
    *  it can rebuild from, and the analyst is told how to move on.
    local _tpl ""
    mata: st_local("_tpl", read_template_version(st_global("processing_dir") + "/" + st_global("processing_file")))
    local _maj = real(word(subinstr("`_tpl'", ".", " ", .), 1))
    local _min = real(word(subinstr("`_tpl'", ".", " ", .), 2))
    if missing(`_min') local _min 0
    *  From 11.1 the package carries its own runtime and settings (ADR-061).
    local _v111 = !missing(`_maj') & (`_maj' > 11 | (`_maj' == 11 & `_min' >= 1))
    if missing(`_maj') | `_maj' < 11 {
        di as txt _n "  NOTE: $processing_file is on a pre-v11 template" _c
        if "`_tpl'" != "" di as txt " (`_tpl')." _c
        di as txt ""
        di as txt    "        It cannot rebuild from the v11 package, so the v10.2.0 package is"
        di as txt    "        built instead. Merge ${processing_file}.new into it to get the v11"
        di as txt    "        package."
        _mdf_deliv_legacy
        cap log close hfc_master
        exit
    }

    if !`_v111' {
        di as error _n "  WARNING: $processing_file is on the `_tpl' template. Its package reads"
        di as error    "           settings baked into that file when it was first generated, and"
        di as error    "           inherits switches left in the Stata session by anything run"
        di as error    "           before it. It may not reproduce the cleaned data. Replace it"
        di as error    "           with ${processing_file}.new (your cleaning is carried into it)."
    }

    di as result _n "--- Building the Deliverables package → $hfcsys_rel_deliv_dir/ ---"

    *  Rebuilt from scratch. The removal is confined to this one folder, and
    *  refuses anything that is not the Deliverables folder of this project.
    local _rm 0
    mata: st_local("_rm", strofreal(_mdf_rmtree_guarded(st_global("deliv_dir"), st_global("ROOT"))))
    if `_rm' != 0 {
        di as error "========================================================================="
        di as error "  DELIVERABLES NOT BUILT — the previous package could not be cleared"
        di as error "========================================================================="
        di as txt   "  A file in $hfcsys_rel_deliv_dir/ is probably open in another program."
        di as txt   "  Close it and run again. The rest of this run is unaffected."
        di as error "========================================================================="
        cap log close hfc_master
        exit 608
    }
    _hfc_mkdir "$deliv_dir"

    local _nds = $actual_n_dta
    local _warn 0
    global hfcsys_dlv_fail 0
    *  The project's short name: the folder a too-long package is told to move
    *  to, and the name of its raw-data global for the load line (ADR-064).
    local _short = substr(ustrregexra("$project_name", "[^A-Za-z0-9]+", "_"), 1, 24)

    forvalues _k = 1/`_nds' {
        local _nm "${auto_dsname_`_k'}"
        local _nn : display %02.0f `_k'
        if `_nds' == 1 local _pk "$deliv_dir"
        else           local _pk "$deliv_dir/`_nn'_`_nm'"
        local _A "`_pk'/01_CAPI & Questionnaire"
        local _B "`_pk'/02_Import & Raw files"
        local _C "`_pk'/03_Processing Files"
        local _D "`_pk'/04_Cleaned Data"
        foreach _d in "`_pk'" "`_A'" "`_B'" "`_C'" "`_C'/01_Do Files" "`_C'/03_Data" "`_D'" {
            _hfc_mkdir "`_d'"
        }
        if `_nds' > 1 di as result _n "  DS`_k' → `_nn'_`_nm'/"

        *==========================================================================*
        *  01  THE FORM AND THE QUESTIONNAIRE
        *==========================================================================*
        *  The form is the one labeling used this run when it ran; otherwise the
        *  one it would use — the override, or the newest in the dataset's folder.
        local _cf "${capi_form_`_k'}"
        if `_nds' == 1 & `"`_cf'"' == "" local _cf "$capi_form"
        if `"`_cf'"' != "" {
            cap confirm file `"`_cf'"'
            if _rc local _cf ""
        }
        if `"`_cf'"' == "" {
            local _fdir ""
            if `_nds' == 1 {
                local _ov "$capi_override"
                local _fdir "$capi_dir"
            }
            else {
                local _ov "${capi_override_`_k'}"
                local _sub : dir "$capi_dir" dirs "`_nn'_SurveyCTO_*", respectcase
                if `"`_sub'"' == "" local _sub : dir "$capi_dir" dirs "`_nn'_*", respectcase
                gettoken _sub1 : _sub
                if `"`_sub1'"' != "" local _fdir "$capi_dir/`_sub1'"
            }
            if `"`_ov'"' != "" {
                cap confirm file "$capi_dir/`_ov'"
                if !_rc local _cf "$capi_dir/`_ov'"
            }
            if `"`_cf'"' == "" & `"`_fdir'"' != "" {
                local _xl : dir "`_fdir'" files "*.xlsx", respectcase
                local _xl : list sort _xl
                foreach _x of local _xl {
                    if substr(`"`_x'"', 1, 1) != "~" local _cf "`_fdir'/`_x'"
                }
            }
        }
        local _cfleaf ""
        if `"`_cf'"' != "" {
            local _cfleaf = ustrregexra(`"`_cf'"', "^.*/", "")
            *  Labeling lists forms without respectcase, so the path it hands
            *  over can carry a lowercased name. The package gets the name the
            *  file really has.
            local _cfdir = substr(`"`_cf'"', 1, strlen(`"`_cf'"') - strlen(`"`_cfleaf'"') - 1)
            local _real ""
            cap local _real : dir "`_cfdir'" files "*.xlsx", respectcase
            foreach _x of local _real {
                if lower(`"`_x'"') == lower(`"`_cfleaf'"') local _cfleaf `"`_x'"'
            }
            local _cf "`_cfdir'/`_cfleaf'"
            _mdf_dlv_copy `"`_cf'"' `"`_A'/`_cfleaf'"'
            if r(ok) di as result "    form          → 01_CAPI & Questionnaire/`_cfleaf'"
            else {
                di as error "    WARNING: could not copy the SurveyCTO form `_cfleaf'."
                local _cfleaf ""
            }
        }
        if "`_cfleaf'" == "" & "$run_labeling" == "1" {
            di as error "    WARNING: no SurveyCTO form found for `_nm'. The package cannot"
            di as error "             label the data, and its Processing DO will stop and say so."
            local _warn = `_warn' + 1
        }

        *  Questionnaire: the dataset's own subfolder, or — with one dataset, or
        *  when nothing is filed per dataset — the top of the questionnaire folder.
        *  Superseded versions (Archive/) do not travel. A second SurveyCTO form
        *  kept among the questionnaires would make the package ambiguous, so
        *  one found here is left out.
        local _qdir ""
        if `_nds' == 1 local _qdir "$quest_dir"
        else {
            local _qs : dir "$quest_dir" dirs "`_nn'_Questionnaire_*", respectcase
            if `"`_qs'"' == "" local _qs : dir "$quest_dir" dirs "`_nn'_*", respectcase
            gettoken _qs1 : _qs
            if `"`_qs1'"' != "" local _qdir "$quest_dir/`_qs1'"
        }
        local _nq 0
        forvalues _pass = 1/2 {
            if `_pass' == 2 {
                if `_nds' == 1 | `_nq' > 0 continue
                local _qdir "$quest_dir"
            }
            if `"`_qdir'"' == "" continue
            local _qf ""
            cap local _qf : dir "`_qdir'" files "*", respectcase
            local _qf : list sort _qf
            foreach _x of local _qf {
                if substr(`"`_x'"', 1, 1) == "~" | substr(`"`_x'"', 1, 1) == "." continue
                if inlist(lower(`"`_x'"'), "desktop.ini", "thumbs.db") continue
                if `"`_x'"' == `"`_cfleaf'"' continue
                if lower(substr(`"`_x'"', -5, 5)) == ".xlsx" {
                    local _isf 0
                    mata: st_local("_isf", strofreal(_mdf_is_xlsform(st_local("_qdir") + "/" + st_local("_x"))))
                    if `_isf' == 1 {
                        di as txt "    left out     : `_x' (a second SurveyCTO form)"
                        continue
                    }
                }
                _mdf_dlv_copy `"`_qdir'/`_x'"' `"`_A'/`_x'"'
                if r(ok) local _nq = `_nq' + 1
            }
        }
        di as result "    questionnaire → 01_CAPI & Questionnaire/ (`_nq' file(s))"

        *==========================================================================*
        *  02  THE RAW DATA, AND THE IMPORT THAT PRODUCED IT
        *==========================================================================*
        *  From the run folder's Raw/ snapshot — what this run processed, not
        *  whatever sits in the raw-data folder today. Identified by the dataset
        *  name, as Master derives it; the date stamp is dropped so the package
        *  carries the name the import DO writes.
        local _snap ""
        local _pos ""
        local _ri 0
        local _raws ""
        cap local _raws : dir "$hfc_raw_snapshot_dir" files "*.dta", respectcase
        local _raws : list sort _raws
        foreach _f of local _raws {
            if strpos(`"`_f'"', "_CLEANED") > 0 | strpos(`"`_f'"', "_LABELED_") > 0 | strpos(`"`_f'"', "_MERGED_") > 0 continue
            local _ri = `_ri' + 1
            local _sn = subinstr(`"`_f'"', "_$hfc_folder_date.dta", "", 1)
            local _sn = subinstr(`"`_sn'"', ".dta", "", 1)
            if strlen(`"`_sn'"') > 5 & lower(substr(`"`_sn'"', -5, 5)) == "_wide" local _sn = substr(`"`_sn'"', 1, strlen(`"`_sn'"') - 5)
            if lower(`"`_sn'"') == lower(`"`_nm'"') & `"`_snap'"' == "" local _snap `"`_f'"'
            if `_ri' == `_k' local _pos `"`_f'"'
        }
        if `"`_snap'"' == "" local _snap `"`_pos'"'
        local _st ""
        local _rawok 0
        local _rsig ""
        local _robs ""
        if `"`_snap'"' != "" {
            local _st = subinstr(`"`_snap'"', "_$hfc_folder_date.dta", "", 1)
            local _st = subinstr(`"`_st'"', ".dta", "", 1)
            _mdf_dlv_copy `"$hfc_raw_snapshot_dir/`_snap'"' `"`_B'/`_st'.dta"'
            local _rawok = r(ok)
            if `_rawok' di as result "    raw data      → 02_Import & Raw files/`_st'.dta"
            else {
                di as error "    WARNING: could not copy the raw dataset `_snap'."
                local _warn = `_warn' + 1
            }
            *  What the package's rebuild will check the raw data against.
            if `_rawok' & `_v111' {
                preserve
                qui use `"`_B'/`_st'.dta"', clear
                qui datasignature
                local _rsig `"`r(datasignature)'"'
                local _robs = _N
                restore
            }
        }
        else {
            di as error "    WARNING: no raw dataset for `_nm' in the run folder — the package"
            di as error "             cannot rebuild it."
            local _warn = `_warn' + 1
        }

        *  The import DO that writes this dataset, found by the file it saves
        *  (its  local dtafile ), with the CSV and corrections file it reads.
        local _imp ""
        foreach _src in "$raw_data_dir" "$processing_data_dir" {
            if `"`_imp'"' != "" continue
            local _dos ""
            cap local _dos : dir "`_src'" files "*.do", respectcase
            local _dos : list sort _dos
            foreach _d of local _dos {
                if `"`_imp'"' != "" continue
                local _dta ""
                local _csv ""
                local _cor ""
                tempname _ih
                cap file open `_ih' using `"`_src'/`_d'"', read text
                if _rc continue
                file read `_ih' _il
                while r(eof) == 0 {
                    foreach _kind in dtafile csvfile corrfile {
                        if strpos(`"`_il'"', "local `_kind'") > 0 {
                            local _p = strpos(`"`_il'"', `"""')
                            if `_p' > 0 {
                                local _rest = substr(`"`_il'"', `_p' + 1, .)
                                local _e = strpos(`"`_rest'"', `"""')
                                if `_e' > 1 {
                                    if "`_kind'" == "dtafile"  & `"`_dta'"' == "" local _dta = substr(`"`_rest'"', 1, `_e' - 1)
                                    if "`_kind'" == "csvfile"  & `"`_csv'"' == "" local _csv = substr(`"`_rest'"', 1, `_e' - 1)
                                    if "`_kind'" == "corrfile" & `"`_cor'"' == "" local _cor = substr(`"`_rest'"', 1, `_e' - 1)
                                }
                            }
                        }
                    }
                    file read `_ih' _il
                }
                cap file close `_ih'
                local _dstem = subinstr(`"`_dta'"', ".dta", "", 1)
                local _cstem = subinstr(`"`_csv'"', ".csv", "", 1)
                if strlen(`"`_cstem'"') > 5 & lower(substr(`"`_cstem'"', -5, 5)) == "_wide" local _cstem = substr(`"`_cstem'"', 1, strlen(`"`_cstem'"') - 5)
                local _hit 0
                if `"`_st'"' != "" & lower(`"`_dstem'"') == lower(`"`_st'"') local _hit 1
                if `"`_dta'"' == "" & lower(`"`_cstem'"') == lower(`"`_nm'"') local _hit 1
                if `_hit' {
                    local _imp `"`_d'"'
                    _mdf_dlv_copy `"`_src'/`_d'"' `"`_B'/`_d'"'
                    if r(ok) di as result "    import DO     → 02_Import & Raw files/`_d'"
                    foreach _aux in _csv _cor {
                        if `"``_aux''"' != "" {
                            cap confirm file `"`_src'/``_aux''"'
                            if !_rc {
                                _mdf_dlv_copy `"`_src'/``_aux''"' `"`_B'/``_aux''"'
                                if r(ok) di as result "    raw export    → 02_Import & Raw files/``_aux''"
                            }
                        }
                    }
                }
            }
        }
        if `"`_imp'"' == "" di as txt "    NOTE: no import DO found for `_nm'; the raw dataset travels on its own."

        *==========================================================================*
        *  03  THE PROCESSING WORKFLOW
        *==========================================================================*
        _mdf_dlv_copy "$processing_dir/$processing_file" `"`_C'/$processing_file"'
        local _procok = r(ok)
        if `_procok' di as result "    workflow      → 03_Processing Files/$processing_file"
        else {
            di as error "    WARNING: could not copy $processing_file into the package."
            local _warn = `_warn' + 1
        }
        *  The package's copy only: one marked line above this dataset's block
        *  that loads its raw data on its own, through the path the package's
        *  INITIALISE sets — so it holds wherever the package is moved.
        if `_v111' & `_procok' & `_rawok' {
            local _lbl "`_nm'"
            if `_nds' > 1 local _lbl "DS`_k': `_nm'"
            local _ll 0
            mata: st_local("_ll", strofreal(_mdf_dlv_loadline(st_local("_C") + "/" + st_global("processing_file"), `_k', st_local("_lbl"), st_local("_st") + ".dta", st_local("_short"))))
            if `_ll' == 1 di as result "    load line     → $processing_file: use .../`_st'.dta, for debugging"
            else if `_ll' == 2 di as result "    load line     : $processing_file has its own (mdf_use)"
            else if `_ll' == -1 {
                di as error "    NOT WRITTEN: $processing_file (adding the dataset's load line)"
                global hfcsys_dlv_fail = $hfcsys_dlv_fail + 1
            }
            else di as txt "    NOTE: DS`_k''s generated block was not found in $processing_file; no load line added."
        }
        *  The two modules the Processing DO calls. Audio, the directory file,
        *  the overrides and the HFC DO serve the project, not the rebuild.
        foreach _m in "01_Labeling.do" "02_Translation.do" {
            cap confirm file "$dofiles_dir/`_m'"
            if !_rc {
                _mdf_dlv_copy "$dofiles_dir/`_m'" `"`_C'/01_Do Files/`_m'"'
                if r(ok) di as result "    module        → 03_Processing Files/01_Do Files/`_m'"
            }
        }

        *  The runtime (ADR-061): the engines this project ran, byte for byte;
        *  the package's own context builder; the framework helpers the DO
        *  files call. The package needs nothing else from this framework.
        *  Hidden like the project's own _mdf/: framework code, not the
        *  client's. It cannot move — the DO files find their package by it.
        if `_v111' {
            local _R "`_C'/01_Do Files/_mdf"
            _hfc_mkdir "`_R'"
            _hfc_mkdir "`_R'/ado"
            _hfc_hide "`_R'" 1
            local _rtn 0
            foreach _e in mdf_labeling mdf_translation {
                _mdf_dlv_copy "$mdf_rt_dir/`_e'.do" `"`_R'/`_e'.do"'
                if r(ok) local _rtn = `_rtn' + 1
            }
            foreach _a in _mdf_rt_package _hfc_abort _hfc_pause _hfc_mkdir mdf_core_vars mdf_finalise _mdf_odk_names mdf_use {
                local _fn ""
                cap findfile `_a'.ado
                if !_rc local _fn `"`r(fn)'"'
                if `"`_fn'"' == "" {
                    di as error "    NOT COPIED: `_a'.ado (not found on the adopath)"
                    global hfcsys_dlv_fail = $hfcsys_dlv_fail + 1
                    continue
                }
                if "`_a'" == "_mdf_rt_package" _mdf_dlv_copy `"`_fn'"' `"`_R'/mdf_runtime.do"'
                else                           _mdf_dlv_copy `"`_fn'"' `"`_R'/ado/`_a'.ado"'
                if r(ok) local _rtn = `_rtn' + 1
            }
            di as result "    runtime       → 03_Processing Files/01_Do Files/_mdf/ (`_rtn' file(s), hidden)"
            *  A module still on an older template brings its own, older
            *  machinery with it, and with it the defects 11.1.0 removed.
            foreach _m in "01_Labeling.do" "02_Translation.do" {
                local _mt ""
                mata: st_local("_mt", read_template_version(st_global("dofiles_dir") + "/`_m'"))
                local _mma = real(word(subinstr("`_mt'", ".", " ", .), 1))
                local _mmi = real(word(subinstr("`_mt'", ".", " ", .), 2))
                if missing(`_mma') | `_mma' < 11 | (`_mma' == 11 & `_mmi' < 1) {
                    di as error "    WARNING: `_m' is on an older template. The package carries it"
                    di as error "             as it is; replace it with `_m'.new for the 11.1 design."
                    local _warn = `_warn' + 1
                }
            }
        }

        *  Translation: the returned files this dataset's rebuild applies. What
        *  was sent out (01_Exported/) is not needed to rebuild and does not
        *  travel. In the package the files sit directly in 02_Translation/ with
        *  one dataset, and in 02_Translation/NN_<dataset>/ with several — the
        *  name the dataset's own package folder has. The package's runtime
        *  reads them there; the folder is made only when there are files.
        *  Sources, as the project's apply step reads them: with several
        *  datasets the dataset's folder under 02_Translated/, else the loose
        *  files naming it; with one dataset 02_Translated/ itself, after any an
        *  earlier build filed under the dataset's own folder, so a newer file
        *  wins a name clash.
        local _trel "02_Translation"
        if `_nds' > 1 local _trel "02_Translation/`_nn'_`_nm'"
        local _srcs `""$translation_dir/02_Translated/`_nm'""'
        if `_nds' == 1 local _srcs `""$translation_dir/02_Translated/`_nm'" "$translation_dir/02_Translated""'
        local _tlist ""
        foreach _td of local _srcs {
            local _tf ""
            cap local _tf : dir "`_td'" files "*", respectcase
            local _tf : list sort _tf
            foreach _x of local _tf {
                if substr(`"`_x'"', 1, 1) != "~" local _tlist `"`_tlist' `"`_td'/`_x'"'"'
            }
        }
        if `"`_tlist'"' == "" & `_nds' > 1 {
            local _tf ""
            cap local _tf : dir "$trans_translated_dir" files "*`_nm'*.xlsx", respectcase
            local _tf : list sort _tf
            foreach _x of local _tf {
                if substr(`"`_x'"', 1, 1) != "~" local _tlist `"`_tlist' `"$trans_translated_dir/`_x'"'"'
            }
        }
        local _ntr 0
        if `"`_tlist'"' != "" {
            _hfc_mkdir "`_C'/02_Translation"
            _hfc_mkdir "`_C'/`_trel'"
            foreach _x of local _tlist {
                local _leaf = ustrregexra(`"`_x'"', "^.*/", "")
                _mdf_dlv_copy `"`_x'"' `"`_C'/`_trel'/`_leaf'"'
                if r(ok) local _ntr = `_ntr' + 1
            }
            di as result "    translation   → 03_Processing Files/`_trel'/ (`_ntr' file(s))"
        }
        else di as txt "    translation   : no returned files, so no 02_Translation/ folder"

        *  Support files the analyst keeps for the cleaning to read. The
        *  framework's own staged copy of the raw export is not one of them: the
        *  raw export travels in 02_Import & Raw files/.
        local _rawn ""
        cap local _rawn : dir "$raw_data_dir" files "*", respectcase
        local _ns 0
        local _pf ""
        cap local _pf : dir "$processing_data_dir" files "*", respectcase
        foreach _x of local _pf {
            if substr(`"`_x'"', 1, 1) == "~" | substr(`"`_x'"', 1, 1) == "." continue
            if inlist(lower(`"`_x'"'), "desktop.ini", "thumbs.db") continue
            local _staged 0
            foreach _y of local _rawn {
                *  Case-blind: staging copies with -dir- lowercasing the name.
                if lower(`"`_x'"') == lower(`"`_y'"') local _staged 1
            }
            if `_staged' continue
            _mdf_dlv_copy `"$processing_data_dir/`_x'"' `"`_C'/03_Data/`_x'"'
            if r(ok) local _ns = `_ns' + 1
        }
        di as result "    support files → 03_Processing Files/03_Data/ (`_ns' file(s))"

        *==========================================================================*
        *  04  THE CLEANED DATASET
        *==========================================================================*
        cap confirm file "$clean_dir/`_nm'_CLEANED.dta"
        if !_rc {
            _mdf_dlv_copy "$clean_dir/`_nm'_CLEANED.dta" `"`_D'/`_nm'_CLEANED.dta"'
            if r(ok) di as result "    cleaned data  → 04_Cleaned Data/`_nm'_CLEANED.dta"
        }
        else {
            di as txt "    NOTE: no cleaned dataset for `_nm' yet — 04_Cleaned Data/ is empty until"
            di as txt "          the package's Processing DO is run."
        }

        if `_v111' {
            *  ── The package's identity and settings (ADR-061) ─────────────────
            local _setf "`_C'/01_Do Files/_mdf/mdf_package.do"
            mata: write_package_settings()
            cap confirm file `"`_setf'"'
            if _rc {
                di as error "    NOT WRITTEN: _mdf/mdf_package.do"
                global hfcsys_dlv_fail = $hfcsys_dlv_fail + 1
            }
            else di as result "    settings      → 03_Processing Files/01_Do Files/_mdf/mdf_package.do"
            _mdf_dlv_readme `"`_pk'"' `"`_nm'"' `_k' `_nds'

            *  ── Every file in it must be openable where it is built ──────────
            local _long ""
            mata: st_local("_long", _mdf_longest(st_local("_pk")))
            if ustrlen(`"`_long'"') > 259 {
                di as error "    PATH TOO LONG (" ustrlen(`"`_long'"') " characters; Windows stops at 260):"
                di as error `"      `_long'"'
                global hfcsys_dlv_fail = $hfcsys_dlv_fail + 1
            }
        }
    }

    if "$merge_required" == "1" {
        di as txt _n "  NOTE: the post-cleaning merge is not part of a per-dataset package;"
        di as txt    "        the merged dataset stays in the project."
    }

    *==============================================================================*
    *  NOTHING FROM THIS MACHINE MAY TRAVEL
    *==============================================================================*
    *  The generated code never names a path. Analyst code can: a line written
    *  with this project's full path would work here and fail at the client's.
    *  Scanned in Mata: a line read into a Stata macro would have its own
    *  macro references expanded on use, and that makes a false match.
    local _mdfr_f = subinstr("$ROOT", "\", "/", .)
    local _mdfr_b = subinstr("$ROOT", "/", "\", .)
    local _leak ""
    local _dirs `""$deliv_dir""'
    if `_nds' > 1 {
        forvalues _k = 1/`_nds' {
            local _nn : display %02.0f `_k'
            local _dirs `"`_dirs' "$deliv_dir/`_nn'_${auto_dsname_`_k'}""'
        }
    }
    foreach _pk of local _dirs {
        foreach _sd in "03_Processing Files" "03_Processing Files/01_Do Files" "03_Processing Files/01_Do Files/_mdf" {
            local _dl ""
            cap local _dl : dir "`_pk'/`_sd'" files "*.do", respectcase
            foreach _x of local _dl {
                local _hit 0
                mata: st_local("_hit", strofreal(_mdf_file_has(st_local("_pk") + "/" + st_local("_sd") + "/" + st_local("_x"), st_local("_mdfr_f"), st_local("_mdfr_b"))))
                if `_hit' local _leak `"`_leak' "`_x'""'
            }
        }
    }
    if `"`_leak'"' != "" {
        di as error _n "  WARNING: these files name this project's folder by its full path:"
        foreach _x of local _leak {
            di as error "             `_x'"
        }
        di as error "           That line will fail on the client's machine. Use the path"
        di as error "           globals instead (e.g. " _char(36) "processing_data_dir)."
        local _warn = `_warn' + 1
    }

    *  A file that did not make it is not a warning: the client would rebuild
    *  a different dataset from what is there and nothing would say so.
    if $hfcsys_dlv_fail > 0 {
        di as error _n "========================================================================="
        di as error    "  DELIVERABLES PACKAGE INCOMPLETE — $hfcsys_dlv_fail file(s) could not be copied"
        di as error    "========================================================================="
        di as txt      "  The files are named above. Do not hand this package over: it cannot"
        di as txt      "  reproduce the cleaned dataset as it stands."
        di as txt      "  Most often the path is too long for Windows (260 characters). Move the"
        di as txt      "  project to a shorter folder (e.g. C:/Projects/<name>) and run again."
        di as error    "========================================================================="
        cap log close hfc_master
        exit 603
    }

    di as result _n "  Deliverables package ready → $hfcsys_rel_deliv_dir/" _c
    if `_warn' > 0 di as error "  (`_warn' warning(s) above)"
    else di as result ""
    cap log close hfc_master
end
