*! mdf_bootstrap.ado — load a project's globals from inside a generated pipeline file
*! version 11.0.0   github.com/adinkhan7/master-do-file
*!
*!  Replaces the generated 04_DO Files/00a_Bootstrap.do (ADR-055).
*!
*!  A generated module resolves its own ROOT — that stays in the module, because
*!  it depends on where the file is being run from and cannot be delegated.
*!  Everything after that is identical for every project and every module, so it
*!  lives here: load the project's directory file if this session has not already.
*!
*!  The directory file sits where the project's layout puts it (ADR-058):
*!    v11   05_Processing/01_Do Files/00a_Directory.do
*!    v10   04_DO Files/00_Directory.do
*!  Files generated by 10.x call this command too, so both are looked for.
*!
*!  The helper programs the old bootstrap defined (_hfc_abort, _hfc_pause,
*!  _hfc_mkdir, _hfc_hide) are ado files in this package now. Stata loads them
*!  from the adopath on demand, which is why they are not redefined here.

program define mdf_bootstrap
    version 16
    args _root

    if "$hfc_dofiles_dir" != "" exit 0

    if `"`_root'"' == "" local _root "$ROOT"
    if `"`_root'"' == "" {
        di as error "mdf_bootstrap: no project root was given and " _char(36) "ROOT is not set."
        di as error "               Run the project's Master DO file once, then retry."
        exit 198
    }

    foreach _cand in "05_Processing/01_Do Files/00a_Directory.do" "04_DO Files/00_Directory.do" {
        cap confirm file `"`_root'/`_cand'"'
        if !_rc {
            do `"`_root'/`_cand'"'
            exit 0
        }
    }

    di as error `"mdf_bootstrap: the project's directory file was not found under `_root'."'
    di as error  "               Run the project's Master DO file once, then retry."
    exit 601
end
