*! mdf_bootstrap.ado — give a generated DO file its project's context
*! version 11.1.0   github.com/adinkhan7/master-do-file
*!
*!  Replaces the generated 04_DO Files/00a_Bootstrap.do (ADR-055).
*!
*!  A file generated by 11.1.0 finds the folder it belongs to by walking up
*!  from Stata's working directory (its INITIALISE block) and hands that folder
*!  here, with its own project name and role in $mdf_want_id / $mdf_want_role.
*!  This command then decides three things, in this order (ADR-061):
*!
*!    1. Which project.  The folder must be a project whose .hfc_root carries
*!       this file's project name. No project found stops the run: the tmpdir
*!       cache is keyed by name, and copies of a project share a name.
*!    2. Reuse or rebuild. A context is reused only when it was loaded for this
*!       very project, and a Processing DO reuses one only while Master itself
*!       is running that project. Otherwise every global is cleared first:
*!       Stata's globals outlive -clear all-, and a context left in the session
*!       by another project, or by a Deliverables package, is not this one.
*!    3. Load. The project's directory file, where its layout keeps it:
*!         v11   05_Processing/01_Do Files/00a_Directory.do
*!         v10   04_DO Files/00_Directory.do
*!
*!  Files generated before 11.1.0 call this with a root and no identity. They
*!  keep working: their context is loaded unless the one already loaded is for
*!  the same root.

program define mdf_bootstrap
    version 16
    args _root

    local _id   `"$mdf_want_id"'
    local _role "$mdf_want_role"
    global mdf_want_id   ""
    global mdf_want_role ""
    global mdf_want_at   ""
    local _root = subinstr(`"`_root'"', "\", "/", .)

    *  ── Files generated before 11.1.0 ───────────────────────────────────────
    if `"`_id'"' == "" {
        if "$hfc_dofiles_dir" != "" & (`"`_root'"' == "" | `"`_root'"' == `"$ROOT"') exit 0
        if `"`_root'"' == "" local _root "$ROOT"
        if `"`_root'"' == "" {
            di as error "mdf_bootstrap: no project root was given and " _char(36) "ROOT is not set."
            di as error "               Run the project's Master DO file once, then retry."
            exit 198
        }
        *  A context from another root is not built on.
        if "$hfc_dofiles_dir" != "" {
            _mdf_load
            mata: _mdf_clear_globals()
        }
        _mdf_boot_load `"`_root'"'
        exit
    }

    *  ── 1. Which project ─────────────────────────────────────────────────────
    *  Nothing above the working directory: stop. The cache the last Master
    *  run wrote (ADR-050) is not consulted for these files. It is keyed by
    *  project NAME, and copies of one project under one name are common — it
    *  would send the run, and its writes, to whichever copy ran last.
    if `"`_root'"' == "" {
        local _pwd `"`c(pwd)'"'
        di as error "======================================================================="
        di as error "  THIS FILE'S PROJECT WAS NOT FOUND"
        di as error "======================================================================="
        di as txt   `"  This file belongs to the project "`_id'". No project or Deliverables"'
        di as txt   "  package was found in Stata's working directory or any folder above it:"
        di as result `"    `_pwd'"'
        di as txt   "  Stata does not tell a DO file where it is saved, so the search starts"
        di as txt   "  at the working directory. Set it to this file's folder (File > Change"
        di as txt   "  Working Directory, or open Stata by double-clicking this file) and run"
        di as txt   "  it again. To run it away from its project, build the Deliverables"
        di as txt   "  package (run_deliverables = 1) and run the copy in that package."
        if strlen(`"`_pwd'"') > 180 {
            di as error "  The working directory is " strlen(`"`_pwd'"') " characters long. Windows cannot open a"
            di as error "  file whose full path passes 260 characters, which can hide a project."
        }
        di as error "======================================================================="
        exit 601
    }
    _mdf_boot_name `"`_root'"'
    local _found `"`r(name)'"'
    *  A running Master is the authority on its own project, even one renamed
    *  since this file was written.
    if `"`_found'"' != "" & `"`_found'"' != `"`_id'"' & `"$mdf_pipeline_root"' != `"`_root'"' {
        di as error "======================================================================="
        di as error "  WRONG PROJECT — NOTHING HAS BEEN RUN"
        di as error "======================================================================="
        di as txt   `"  This file belongs to the project : `_id'"'
        di as txt   `"  The project found here is        : `_found'"'
        di as result `"    `_root'"'
        di as txt   "  It was found by searching upward from Stata's working directory, which"
        di as txt   "  is inside another project. Set the working directory to this file's own"
        di as txt   "  project and run it again. If the project was renamed in Master Section"
        di as txt   "  0, run Master once and use the files it generates for the new name."
        di as error "======================================================================="
        exit 198
    }

    *  ── 2. Reuse or rebuild ──────────────────────────────────────────────────
    local _same 0
    if `"$ROOT"' == `"`_root'"' & "$hfc_dofiles_dir" != "" & "$mdf_package" != "1" local _same 1
    if "`_role'" == "processing" & `"$mdf_pipeline_root"' != `"`_root'"' local _same 0
    if `_same' exit 0

    *  Every global, not the locals of this command (macro drop _all would
    *  take those too — measured).
    _mdf_load
    mata: _mdf_clear_globals()

    *  ── 3. Load ──────────────────────────────────────────────────────────────
    di as result `"Project root → `_root'"'
    _mdf_boot_load `"`_root'"'
end

*  The directory file of a project, run with ROOT fixed to that project.
program define _mdf_boot_load
    version 16
    args _root

    *  Find first, run after the loop. Under -version 16- a zero -exit- inside a
    *  loop does not leave the program, it only ends the iteration: the loop
    *  ran the directory file, went on to the next candidate, and fell through
    *  to the error below. Measured in Stata 17.
    local _dirfile ""
    foreach _cand in "05_Processing/01_Do Files/00a_Directory.do" "04_DO Files/00_Directory.do" {
        if `"`_dirfile'"' == "" {
            cap confirm file `"`_root'/`_cand'"'
            if !_rc local _dirfile `"`_root'/`_cand'"'
        }
    }
    if `"`_dirfile'"' == "" {
        di as error `"mdf_bootstrap: the project's directory file was not found under `_root'."'
        di as error  "               Run the project's Master DO file once, then retry."
        exit 601
    }
    *  The directory file keeps a ROOT it is given, and derives one otherwise.
    global ROOT `"`_root'"'
    global hfc_dofiles_dir ""
    do `"`_dirfile'"'
end

*  The project name a .hfc_root sentinel records, in r(name).
program define _mdf_boot_name, rclass
    version 16
    args _root
    local _nm ""
    tempname _fh
    cap file open `_fh' using `"`_root'/.hfc_root"', read text
    if !_rc {
        file read `_fh' _ln
        while r(eof) == 0 {
            if strpos(`"`_ln'"', "project_name") == 1 {
                local _eq = strpos(`"`_ln'"', "=")
                if `_eq' > 0 local _nm = strtrim(substr(`"`_ln'"', `_eq' + 1, .))
            }
            file read `_fh' _ln
        }
        file close `_fh'
    }
    return local name `"`_nm'"'
end
