*! mdf_readme.ado — Master DO File pipeline stage 5 of 19
*! version 11.1.3   github.com/adinkhan7/master-do-file
*!
*!  write the project README
*!
*!  Folder names come from the path globals, so the README describes the
*!  layout this project actually uses — v11, or the v10 layout an older
*!  project keeps (ADR-058).

program define mdf_readme
    version 16
    *  A clean stop upstream (Run 1, a CAPI pause, a Ghost Run) sets this.
    *  `exit` inside an ado returns from the ado, not from Master, so every
    *  later stage has to stand down of its own accord.
    if "$mdf_halt" == "1" exit

    _mdf_load

    *==============================================================================*
    *  SECTION 5   README
    *==============================================================================*

    local Q  "$hfcsys_rel_quest_dir"
    local C  "$hfcsys_rel_capi_dir"
    local D  "$hfcsys_rel_data_dir"
    local O  "$hfcsys_rel_others_dir"
    local P  "$hfcsys_rel_processing_dir"
    local F  "$hfcsys_rel_dofiles_dir"
    local T  "$hfcsys_rel_translation_dir"
    local PD "$hfcsys_rel_processing_data_dir"
    local H  "$hfcsys_rel_hfc_dir"
    local K  "$hfcsys_rel_clean_dir"
    local V  "$hfcsys_rel_deliv_dir"
    local DF "$directory_file"

    tempname _mf
    cap file open `_mf' using "$ROOT/README.md", write replace text
    if !_rc {
        file write `_mf' "# $project_name — Project Guide" _n _n
        file write `_mf' "Generated by Master DO File $hfc_version on $today. Layout: $hfc_layout_version." _n
        file write `_mf' "This file is regenerated on every run. Do not edit it." _n _n
        if "$hfc_layout_version" == "v10" {
            file write `_mf' "This project was built before v11 and keeps its original folder layout." _n
            file write `_mf' "Nothing in it is moved: v11 runs it on the folders it already has." _n _n
        }
        file write `_mf' "## Ownership tiers" _n _n
        file write `_mf' "| Tier | Meaning | On the next run |" _n
        file write `_mf' "|---|---|---|" _n
        file write `_mf' "| 1 framework | Master's alone | always overwritten |" _n
        file write `_mf' "| 2 shared | Master generates, you edit | never overwritten; a .new copy appears when the template moves |" _n
        file write `_mf' "| 3 analyst | yours | never touched after creation |" _n _n
        file write `_mf' "## Files" _n _n
        file write `_mf' "| Path | Role | Tier |" _n
        file write `_mf' "|---|---|---|" _n
        file write `_mf' "| .hfc_root | project sentinel; ROOT detection | 1 |" _n
        file write `_mf' "| README.md | this file | 1 |" _n
        file write `_mf' "| `Q'/ | questionnaire documents | analyst input |" _n
        file write `_mf' "| `C'/ | SurveyCTO form(s); superseded versions in Archive/ | analyst input |" _n
        file write `_mf' "| `D'/ | dated raw SurveyCTO exports + import DOs | analyst input |" _n
        file write `_mf' "| `O'/ | supporting and preload material | analyst input |" _n
        file write `_mf' "| `P'/${project_name}_Processing.do | THE cleaning file; produces the cleaned dataset | 2 |" _n
        file write `_mf' "| `F'/`DF' | all path globals; single source of truth | 1 |" _n
        file write `_mf' "| `F'/00b_Local_Overrides.do | your machine-specific overrides | 3 |" _n
        file write `_mf' "| `F'/01_Labeling.do | CAPI value labels, then YOUR manual labels | 2 |" _n
        file write `_mf' "| `F'/02_Translation.do | returned translations, then YOUR manual overrides; export | 2 |" _n
        file write `_mf' "| `F'/03_Audio.do | audio sampling for back-checks | 2 |" _n
        file write `_mf' "| `F'/_mdf/ | framework runtime: the labeling and translation engines (hidden) | 1 |" _n
        file write `_mf' "| `T'/ | 01_Exported (sent out), 02_Translated (returned) | analyst work |" _n
        file write `_mf' "| `PD'/ | the current working data; your own support files for cleaning | analyst work |" _n
        file write `_mf' "| `H'/02_${project_name}_HFC.do | the check script | 2 |" _n
        file write `_mf' "| `H'/KEYS/ | key snapshots, breadcrumb, issue-flag stores | 1 |" _n
        file write `_mf' "| `H'/NN_..._HFC_YYYYMMDD/ | one folder per run: report, audio list, log, datasets | 1 |" _n
        file write `_mf' "| `K'/ | current cleaned data — what every consumer reads | 1 |" _n
        file write `_mf' "| `V'/ | client handover package, built when run_deliverables = 1 | 1 |" _n _n
        file write `_mf' "## Running it" _n _n
        file write `_mf' "Edit SECTION 0 of the Master DO file, then run it. Nothing else needs" _n
        file write `_mf' "editing. The run happens in three phases:" _n _n
        file write `_mf' "1. **Run 1** builds the folder tree and stops. Put the questionnaire in" _n
        file write `_mf' "   `Q'/, the SurveyCTO .xlsx form in `C'/, and the import DO + CSV" _n
        file write `_mf' "   from the server in `D'/." _n
        file write `_mf' "2. **Run 2** detects the import DO(s) and generates the pipeline files." _n
        file write `_mf' "3. **Run 3 onward** runs the pipeline." _n _n
        file write `_mf' "With more than one dataset, Run 2 creates one subfolder per dataset in" _n
        file write `_mf' "`C'/ and `Q'/ and asks for each form before it continues." _n _n
        file write `_mf' "## The stage switches" _n _n
        file write `_mf' "| Switch | What it does |" _n
        file write `_mf' "|---|---|" _n
        file write `_mf' "| run_import | run the SurveyCTO import DO(s) |" _n
        file write `_mf' "| run_labeling | apply CAPI value labels — happens INSIDE processing |" _n
        file write `_mf' "| run_translation | open-ended round trip |" _n
        file write `_mf' "| run_processing | produce the cleaned dataset |" _n
        file write `_mf' "| run_hfc | run the checks and write the report |" _n
        file write `_mf' "| run_audio | draw the audio back-check sample |" _n
        file write `_mf' "| run_deliverables | build the client handover package in `V'/ (see Deliverables below) |" _n
        file write `_mf' "| post_field | fieldwork is over: re-run the last run folder instead of starting a new one (see Post-field mode below) |" _n _n
        file write `_mf' "**Labeling and applying translations both happen inside processing**, per" _n
        file write `_mf' "dataset, immediately before that dataset is cleaned. Setting run_labeling = 1" _n
        file write `_mf' "with run_processing = 0 therefore labels nothing, and the run says so." _n _n
        file write `_mf' "**Archiving is not a switch.** Raw data is copied into the dated run folder" _n
        file write `_mf' "on every run, because labeling reads from there and dataset detection" _n
        file write `_mf' "depends on it." _n _n
        file write `_mf' "## The open-ended translation round trip" _n _n
        file write `_mf' "Set exportopenended = 1 to send text out. Name the variables to send in" _n
        file write `_mf' "exp_openended_vars (one dataset) or exp_openended_vars_1, _2, _3 (one list per" _n
        file write `_mf' "dataset, when there are several); wildcards such as q5_* work, and left empty" _n
        file write `_mf' "every text variable is sent." _n _n
        file write `_mf' "With ONE dataset the files sit directly in `T'/01_Exported/ and" _n
        file write `_mf' "`T'/02_Translated/. With several datasets each has its own subfolder in both," _n
        file write `_mf' "`T'/01_Exported/<dataset>/ and `T'/02_Translated/<dataset>/, so their files" _n
        file write `_mf' "stay apart. Return the completed file to the matching 02_Translated folder under" _n
        file write `_mf' "any filename, keeping the key and variable columns untouched, and fill the" _n
        file write `_mf' "translated column. inputcorrection = 1 applies everything found there on the" _n
        file write `_mf' "next run. (A one-dataset project that already has files in" _n
        file write `_mf' "`T'/02_Translated/<dataset>/ keeps working: those are applied too.)" _n _n
        file write `_mf' "Only rows not previously sent are exported. Set oe_export_all = 1 to send" _n
        file write `_mf' "everything again." _n _n
        file write `_mf' "You can leave the SurveyCTO form open in Excel while running; labeling is" _n
        file write `_mf' "unaffected." _n _n
        file write `_mf' "## What the processing file does, in order" _n _n
        file write `_mf' "For each dataset, in its own block:" _n _n
        file write `_mf' "1. **Label** — 01_Labeling.do applies CAPI value labels and leaves the" _n
        file write `_mf' "   dataset in memory. No _LABELED_ file is written." _n
        file write `_mf' "2. **Apply translations** — anything returned in `T'/02_Translated/" _n
        file write `_mf' "   is injected BEFORE your cleaning runs, so your rules see translated text." _n
        file write `_mf' "3. **Core variables** — mdf_core_vars derives fielddate from starttime" _n
        file write `_mf' "   and total_duration from duration, when the import did not supply them." _n
        file write `_mf' "4. **Your cleaning** — SECTION A (field fixes that must reach today's HFC)" _n
        file write `_mf' "   then SECTION B (final recodes). Both always run, every day." _n
        file write `_mf' "5. **Save** — the cleaned dataset, dated, into the run folder." _n _n
        file write `_mf' "Then once, after all datasets:" _n _n
        file write `_mf' "6. **Merge** — mdf_finalise merge, if merge_required = 1." _n
        file write `_mf' "7. **Export open-ended** — only if exportopenended = 1. It runs after" _n
        file write `_mf' "   cleaning so a translator receives cleaned rows, not raw ones." _n
        file write `_mf' "8. **Publish** — mdf_finalise publish copies each cleaned dataset to" _n
        file write `_mf' "   `K'/ under a stable, undated name." _n _n
        file write `_mf' "Files your cleaning reads (a lookup table, a list of corrections) belong in" _n
        file write `_mf' "`PD'/ and are best read through the global processing_data_dir, so" _n
        file write `_mf' "the same line works in the project and in the Deliverables package." _n _n
        file write `_mf' "## Configuration reference" _n
        file write `_mf' "" _n
        file write `_mf' "Every setting lives in SECTION 0 of the Master DO file. The ones whose" _n
        file write `_mf' "meaning is not obvious from the line itself:" _n
        file write `_mf' "" _n
        file write `_mf' "| Setting | Accepted values |" _n
        file write `_mf' "|---|---|" _n
        file write `_mf' "| capi_override | leave empty to auto-detect the most recent .xlsx in `C'/, or name one form |" _n
        file write `_mf' "| capi_language | the ODKSplit label language, e.g. English |" _n
        file write `_mf' "| capi_verbose | 1 prints the ODKSplit variable list, 0 labels silently |" _n
        file write `_mf' "| oe_export_all | 0 exports only rows never sent before, 1 re-exports everything |" _n
        file write `_mf' "| exp_openended_vars, exp_openended_vars_1..3 | the open-ended variables to export for translation: exp_openended_vars for one dataset, the numbered lists for several; empty = every text variable |" _n
        file write `_mf' "| project_analyst, project_email, organisation, project_description | printed in the header of every generated DO file; a field left empty is left out |" _n
        file write `_mf' "| audio_drop_before | leave empty to drop interviews before yesterday, or give a fixed YYYYMMDD |" _n
        file write `_mf' "| audio_keep_enums | leave empty to sample every enumerator, or give space-separated numeric enum IDs, e.g. 1 2 5 |" _n
        file write `_mf' "| audio_seed | fixes the sample so the same run reproduces the same draw |" _n
        file write `_mf' "| merge_datasets | space-separated dataset indices, e.g. 1 3 |" _n
        file write `_mf' "| import_fingerprint | 1 re-imports only when the raw export actually changed |" _n
        file write `_mf' "| hfc_excel_aliases, hfc_dta_aliases | extra global names pointing at the report and the target dataset, so existing team code keeps working |" _n
        file write `_mf' "| verbose | 1 runs each stage so Stata's errors print, 0 runs them silently |" _n
        file write `_mf' "" _n
        file write `_mf' "The variable lists (meta_front, meta_ids, tail, timer_start, timer_end) name" _n
        file write `_mf' "the columns the checks treat as identifiers, front matter and trailing" _n
        file write `_mf' "metadata. With more than one dataset, use the numbered forms: meta_front_1," _n
        file write `_mf' "meta_ids_1 and so on, one set per dataset." _n
        file write `_mf' "" _n
        file write `_mf' "## Dataset naming" _n
        file write `_mf' "" _n
        file write `_mf' "A dataset takes its name from the import DO file. SurveyCTO appends _wide to" _n
        file write `_mf' "the export of a form containing repeat groups; Master strips that suffix, so" _n
        file write `_mf' "form_one_wide becomes the dataset form_one. Datasets are numbered DS1, DS2 ..." _n
        file write `_mf' "in the sorted order of their names. Files written into a run folder carry the" _n
        file write `_mf' "stage and the date, for example form_one_CLEANED_20260824.dta." _n
        file write `_mf' "" _n
        file write `_mf' "## Missing core variables" _n
        file write `_mf' "" _n
        file write `_mf' "The checks need key, enum, fielddate and duration. When an import does not" _n
        file write `_mf' "supply fielddate or total_duration, mdf_core_vars derives them from" _n
        file write `_mf' "starttime and duration. If a variable cannot be derived at all, the checks" _n
        file write `_mf' "that need it are skipped with a message rather than failing the run." _n
        file write `_mf' "" _n
        file write `_mf' "## Where your own changes go" _n
        file write `_mf' "" _n
        file write `_mf' "Every generated DO file marks its sections [SAFE TO EDIT] or [MDF GENERATED" _n
        file write `_mf' "- DO NOT EDIT]. Master never overwrites these files once they exist." _n
        file write `_mf' "" _n
        file write `_mf' "- Cleaning rules: the Processing DO, sections 2 (field cleaning) and 3" _n
        file write `_mf' "  (post-field cleaning), one pair per dataset." _n
        file write `_mf' "- Labels the CAPI form cannot supply: 01_Labeling.do, MANUAL LABELING." _n
        file write `_mf' "- A variable odksplit cannot handle by its own name: 01_Labeling.do," _n
        file write `_mf' "  ODKSPLIT NAME OVERRIDES. Names of 29+ characters are handled without" _n
        file write `_mf' "  being listed: for odksplit only they take a short temporary name" _n
        file write `_mf' "  (_mdf001, ...), and the log shows each one and its restoration." _n
        file write `_mf' "- Corrections the returned translation files do not carry:" _n
        file write `_mf' "  02_Translation.do, MANUAL TRANSLATION OVERRIDES." _n
        file write `_mf' "- Check thresholds and your own checks: the HFC DO, CHECK SETTINGS and" _n
        file write `_mf' "  CUSTOM CHECKS." _n
        file write `_mf' "" _n
        file write `_mf' "When the framework's template for one of these files changes, Master" _n
        file write `_mf' "writes the new version beside yours as <file>.new. For the Processing DO" _n
        file write `_mf' "the .new already carries your cleaning code; review it, then replace your" _n
        file write `_mf' "file with it. The header of each file (project analyst, organisation," _n
        file write `_mf' "contact, description) comes from the project details in Section 0." _n
        file write `_mf' "" _n
        file write `_mf' "## Running a DO file on its own" _n
        file write `_mf' "" _n
        file write `_mf' "Stata does not tell a running DO file where it is saved. Every generated" _n
        file write `_mf' "file therefore searches upward from Stata's WORKING DIRECTORY for its" _n
        file write `_mf' "project (or its Deliverables package), checks that what it found is its" _n
        file write `_mf' "own project by name, and loads that project's settings - never anything" _n
        file write `_mf' "left in the Stata session by another project or package. Launching Stata" _n
        file write `_mf' "by double-clicking a DO file sets the working directory to its folder;" _n
        file write `_mf' "otherwise use File > Change working directory." _n
        file write `_mf' "" _n
        file write `_mf' "The Processing DO, 01_Labeling.do, 02_Translation.do and 03_Audio.do run" _n
        file write `_mf' "only inside this project or inside a Deliverables package. Anywhere else" _n
        file write `_mf' "they stop, write nothing, and say where to run them. To carry the" _n
        file write `_mf' "processing away, build the Deliverables package (below)." _n
        file write `_mf' "" _n
        file write `_mf' "## Standalone mode (the HFC DO)" _n
        file write `_mf' "" _n
        file write `_mf' "The HFC DO still works when it is copied away from this project. Put it" _n
        file write `_mf' "in a folder with the dataset(s) it should check and run it: finding no" _n
        file write `_mf' "project above itself, it builds a small context from that folder instead." _n
        file write `_mf' "It announces this, naming the folder and every dataset it picked up." _n
        file write `_mf' "" _n
        file write `_mf' "Nothing outside that folder is read or written, the Master DO File is not" _n
        file write `_mf' "needed, the framework package does not have to be installed, and no" _n
        file write `_mf' "network connection is used." _n
        file write `_mf' "" _n
        file write `_mf' "  Supported   the HFC DO." _n
        file write `_mf' "  Inputs      *.dta beside the DO, or in the first of Data/, 02_Data/," _n
        file write `_mf' "              01_Data/ or 03_Data/ that holds any. Sorted by name: first" _n
        file write `_mf' "              is DS1, second DS2. Framework output (*_CLEANED, *_KEYS_," _n
        file write `_mf' "              *_MERGED_, *_LABELED_) is never counted, so a second run" _n
        file write `_mf' "              cannot read the first run's results as input." _n
        file write `_mf' "  Output      MDF_Output/ beside the DO." _n
        file write `_mf' "  Settings    whatever Section 0 held when the file was generated." _n
        file write `_mf' "" _n
        file write `_mf' "It stops rather than guess. No dataset in the folder, or a number that" _n
        file write `_mf' "does not match what the file was generated for, ends the run with a" _n
        file write `_mf' "message naming the folder and listing what it found." _n
        file write `_mf' "" _n
        file write `_mf' "**Where Stata looks.** Stata does not tell a running DO file where it is" _n
        file write `_mf' "saved — not when it is run from the Do button, and not with Ctrl+A then" _n
        file write `_mf' "Ctrl+D. Every generated file therefore starts from Stata's WORKING" _n
        file write `_mf' "DIRECTORY. Launching Stata by double-clicking the DO sets it to the DO's" _n
        file write `_mf' "folder; otherwise use File > Change working directory first. A run that" _n
        file write `_mf' "looks in the wrong place says so and names the folder it searched." _n
        file write `_mf' "" _n
        file write `_mf' "Inside this project nothing changes: the project is found first and every" _n
        file write `_mf' "file behaves exactly as it always has." _n
        file write `_mf' "" _n
        file write `_mf' "## Post-field mode" _n
        file write `_mf' "" _n
        file write `_mf' "Set post_field = 1 in Section 0 once fieldwork is over and no new export will" _n
        file write `_mf' "arrive. Set it back to 0 to return to normal dated runs." _n
        file write `_mf' "" _n
        file write `_mf' "- **post_field = 0 (normal).** Each dated run creates today's raw-data and" _n
        file write `_mf' "  run folders, imports the export, processes it, and stamps its outputs" _n
        file write `_mf' "  with today's date." _n
        file write `_mf' "- **post_field = 1.** Master re-runs the last run folder that holds data. It" _n
        file write `_mf' "  creates no new folder and imports nothing (run_import is switched off)." _n
        file write `_mf' "  Everything it writes is stamped with THAT folder's date, so a re-run" _n
        file write `_mf' "  reproduces the same files in place instead of scattering new dated" _n
        file write `_mf' "  ones. The run log alone keeps the real calendar date, so earlier logs" _n
        file write `_mf' "  are not overwritten." _n
        file write `_mf' "" _n
        file write `_mf' "Use it for the cleaning and delivery work after the last data has been" _n
        file write `_mf' "downloaded: re-running the Processing DO, the HFC, or building the" _n
        file write `_mf' "Deliverables. If no run folder in `H'/ holds any data, the run stops and" _n
        file write `_mf' "says so: set post_field = 0, put the export in `D'/ and run once." _n
        file write `_mf' "" _n
        file write `_mf' "## Deliverables" _n
        file write `_mf' "" _n
        file write `_mf' "Set run_deliverables = 1 in Section 0 and the next run rebuilds `V'/" _n
        file write `_mf' "from scratch. It holds only what a client needs to understand the survey" _n
        file write `_mf' "and reproduce the cleaned dataset — no daily download folders, no check" _n
        file write `_mf' "history, no keys, no logs, no Master. One dataset:" _n
        file write `_mf' "" _n
        file write `_mf' "    `V'/" _n
        file write `_mf' "      01_CAPI & Questionnaire/   the current form and questionnaire" _n
        file write `_mf' "      02_Import & Raw files/     the raw dataset, its import DO and CSV" _n
        file write `_mf' "      03_Processing Files/       ${project_name}_Processing.do" _n
        file write `_mf' "        01_Do Files/             01_Labeling.do, 02_Translation.do" _n
        file write `_mf' "          _mdf/  (hidden)        the runtime: the engines this project ran," _n
        file write `_mf' "                                 the package's settings (mdf_package.do)" _n
        file write `_mf' "        02_Translation/          the returned translation files, if any" _n
        file write `_mf' "        03_Data/                 your support files from `PD'/" _n
        file write `_mf' "      04_Cleaned Data/           the cleaned dataset" _n
        file write `_mf' "      README.md                  how the client rebuilds it" _n
        file write `_mf' "" _n
        file write `_mf' "With more than one dataset the same four folders appear once per dataset," _n
        file write `_mf' "under `V'/NN_<dataset>/, each holding only that dataset, its returned" _n
        file write `_mf' "translation files in 02_Translation/NN_<dataset>/. The post-cleaning merge" _n
        file write `_mf' "is not part of a per-dataset package. Its Processing DO keeps the LOAD" _n
        file write `_mf' "DATASET lines (below), and they work there too." _n
        file write `_mf' "" _n
        file write `_mf' "**How the client reproduces it.** Copy the folder anywhere, open" _n
        file write `_mf' "03_Processing Files/${project_name}_Processing.do in Stata and run it" _n
        file write `_mf' "(Ctrl+A, then Ctrl+D). The file recognises the package around it, reads the" _n
        file write `_mf' "raw data from 02_Import & Raw files/, and writes the cleaned dataset into" _n
        file write `_mf' "04_Cleaned Data/. Neither this project nor the Master DO File framework is" _n
        file write `_mf' "needed. The survey commands it uses (odksplit, inputcorrection) are" _n
        file write `_mf' "installed on first run if the machine lacks them; if that is impossible" _n
        file write `_mf' "the run stops rather than produce a dataset that would not match." _n
        file write `_mf' "" _n
        file write `_mf' "The package's DO needs Stata's working directory to be inside the package" _n
        file write `_mf' "— double-clicking the DO does this — and says so if it is not." _n
        file write `_mf' "" _n
        file write `_mf' "**What the rebuild checks.** Every setting comes from the package's own" _n
        file write `_mf' "_mdf/mdf_package.do, written when it was built, never from the Stata" _n
        file write `_mf' "session. Before anything runs it confirms that the package is this file's" _n
        file write `_mf' "project, that no path is too long for Windows, and that the raw dataset is" _n
        file write `_mf' "the one it was built from, by name and by datasignature; anything else" _n
        file write `_mf' "stops the run. At the end it compares the rebuilt dataset with the one" _n
        file write `_mf' "shipped in 04_Cleaned Data/ and reports REPRODUCED or NOT REPRODUCED." _n
        if "$hfc_layout_version" == "v10" {
            file write `_mf' "" _n
            file write `_mf' "A Processing DO still on a pre-v11 template cannot recognise this package;" _n
            file write `_mf' "until its .new has been merged, run_deliverables builds the flat v10.2.0" _n
            file write `_mf' "package (Data/, CAPI/, Clean_Reference/, output in MDF_Output/) instead." _n
        }
        file write `_mf' "" _n
        file write `_mf' "## Working on one block of code" _n _n
        file write `_mf' "Every generated DO file has LOAD DATASET lines, one per dataset: above each" _n
        file write `_mf' "dataset's block in the Processing DO, and right after section 0 in the" _n
        file write `_mf' "Labeling, Translation, Audio and HFC DOs. To run a block without" _n
        file write `_mf' "everything above it: run section 0. INITIALISE once (select it, Ctrl+D)," _n
        file write `_mf' "then select the dataset's line and press Ctrl+D." _n
        file write `_mf' "" _n
        file write `_mf' "- Processing, Labeling, Translation: mdf_use k, project(...) puts the" _n
        file write `_mf' "  dataset's RAW data in memory, the file the labeling step loads. Labels and" _n
        file write `_mf' "  translations are applied by running the lines below it." _n
        file write `_mf' "- Audio, HFC: the dataset the file works on, the cleaned dataset if there" _n
        file write `_mf' "  is one, else raw." _n
        file write `_mf' "" _n
        file write `_mf' "A full run of the file skips these lines. mdf_use loads nothing, and says" _n
        file write `_mf' "why, when section 0 has not been run or another project's settings are" _n
        file write `_mf' "in Stata." _n
        file write `_mf' "" _n
        file write `_mf' "## Where the explanations live" _n _n
        file write `_mf' "The generated DO files carry headings, not essays. Why the framework is" _n
        file write `_mf' "shaped this way is recorded once, in Instruction/DECISIONS.md, as a set of" _n
        file write `_mf' "numbered decisions. The code itself stays free of them." _n _n
        file write `_mf' "## If a run fails" _n _n
        file write `_mf' "The run stops and prints the stage that failed, Stata's own error message," _n
        file write `_mf' "the file it happened in, and the log path. Read the last screen first." _n _n
        file write `_mf' "## Reproducing a past run" _n _n
        file write `_mf' "Each `H'/NN_..._HFC_YYYYMMDD/ folder holds the dated dataset snapshot the" _n
        file write `_mf' "report for that date was computed from. `K'/ always holds the" _n
        file write `_mf' "CURRENT data; the dated snapshot is what reproduces history." _n
        file close `_mf'
        di as result _n "README.md written."
    }
    else di as error "WARNING: could not write README.md."

    *  ── CAPI verification ──────────────────────────────────────────────────────
    di as result "CAPI directory initialization: OK"
end
