*! mdf_readme.ado — Master DO File pipeline stage 5 of 18
*! version 10.2.0   github.com/adinkhan7/master-do-file
*!
*!  write the project README

program define mdf_readme
    version 16
    *  A clean stop upstream (Run 1, a CAPI pause, a Ghost Run) sets this.
    *  `exit` inside an ado returns from the ado, not from Master, so every
    *  later stage has to stand down of its own accord.
    if "$mdf_halt" == "1" exit

    _mdf_load

    *==============================================================================*
    *  SECTION 5   README
    *==============================================================================*

    tempname _mf
    cap file open `_mf' using "$ROOT/README.md", write replace text
    if !_rc {
        file write `_mf' "# $project_name — Project Guide" _n _n
        file write `_mf' "Generated by Master DO File $hfc_version on $today. Layout: $hfc_layout_version." _n
        file write `_mf' "This file is regenerated on every run. Do not edit it." _n _n
        file write `_mf' "## Ownership tiers" _n _n
        file write `_mf' "| Tier | Meaning | On the next run |" _n
        file write `_mf' "|---|---|---|" _n
        file write `_mf' "| 1 framework | Master's alone | always overwritten |" _n
        file write `_mf' "| 2 shared | Master generates, you edit | never overwritten; a .new copy appears when the template moves |" _n
        file write `_mf' "| 3 analyst | yours | never touched after creation |" _n _n
        file write `_mf' "## Files" _n _n
        file write `_mf' "| Path | Role | Tier |" _n
        file write `_mf' "|---|---|---|" _n
        file write `_mf' "| .hfc_root | project sentinel; ROOT detection | 1 |" _n
        file write `_mf' "| README.md | this file | 1 |" _n
        file write `_mf' "| 01_Survey_Instruments/ | questionnaire + CAPI forms (superseded versions in Archive/) | analyst input |" _n
        file write `_mf' "| 02_Data/ | dated raw SurveyCTO exports + import DOs | analyst input |" _n
        file write `_mf' "| 03_HFC/02_${project_name}_HFC.do | the check script | 2 |" _n
        file write `_mf' "| 03_HFC/KEYS/ | key snapshots, breadcrumb, issue-flag stores | 1 |" _n
        file write `_mf' "| 03_HFC/NN_..._HFC_YYYYMMDD/ | one folder per run: report, audio list, log, datasets | 1 |" _n
        file write `_mf' "| 04_DO Files/00_Directory.do | all path globals; single source of truth | 1 |" _n
        file write `_mf' "| 04_DO Files/00b_Local_Overrides.do | your machine-specific overrides | 3 |" _n
        file write `_mf' "| 04_DO Files/01_Labeling.do | CAPI value labels via ODKSplit | 2 |" _n
        file write `_mf' "| 04_DO Files/02_Translation.do | open-ended export/re-import round trip | 2 |" _n
        file write `_mf' "| 04_DO Files/03_Audio.do | audio sampling for back-checks | 2 |" _n
        file write `_mf' "| 05_Translation/ | 01_Exported (sent out), 02_Translated (returned) | analyst work |" _n
        file write `_mf' "| 06_Processing Files/${project_name}_Processing.do | THE cleaning file; produces the cleaned dataset | 2 |" _n
        file write `_mf' "| 07_Cleaned Dataset/ | current cleaned data — what every consumer reads | 1 |" _n _n
        file write `_mf' "## Running it" _n _n
        file write `_mf' "Edit SECTION 0 of the Master DO file, then run it. Nothing else needs" _n
        file write `_mf' "editing. The run happens in three phases:" _n _n
        file write `_mf' "1. **Run 1** builds the folder tree and stops. Put the questionnaire in" _n
        file write `_mf' "   01_Survey_Instruments/01_Questionnaire/, the SurveyCTO .xlsx form in" _n
        file write `_mf' "   02_CAPI/, and the import DO + CSV from the server in 02_Data/." _n
        file write `_mf' "2. **Run 2** detects the import DO(s) and generates the pipeline files." _n
        file write `_mf' "3. **Run 3 onward** runs the pipeline." _n _n
        file write `_mf' "## The stage switches" _n _n
        file write `_mf' "| Switch | What it does |" _n
        file write `_mf' "|---|---|" _n
        file write `_mf' "| run_import | run the SurveyCTO import DO(s) |" _n
        file write `_mf' "| run_labeling | apply CAPI value labels — happens INSIDE processing |" _n
        file write `_mf' "| run_translation | open-ended round trip |" _n
        file write `_mf' "| run_processing | produce the cleaned dataset |" _n
        file write `_mf' "| run_hfc | run the checks and write the report |" _n
        file write `_mf' "| run_audio | draw the audio back-check sample |" _n _n
        file write `_mf' "**Labeling and applying translations both happen inside processing**, per" _n
        file write `_mf' "dataset, immediately before that dataset is cleaned. Setting run_labeling = 1" _n
        file write `_mf' "with run_processing = 0 therefore labels nothing, and the run says so." _n _n
        file write `_mf' "**Archiving is not a switch.** Raw data is copied into the dated run folder" _n
        file write `_mf' "on every run, because labeling reads from there and dataset detection" _n
        file write `_mf' "depends on it." _n _n
        file write `_mf' "## The open-ended translation round trip" _n _n
        file write `_mf' "Set exportopenended = 1 to send text out. Files land in" _n
        file write `_mf' "05_Translation/01_Exported/<dataset>/. Return the completed file to" _n
        file write `_mf' "05_Translation/02_Translated/<dataset>/ under any filename, keeping the" _n
        file write `_mf' "key and variable columns untouched, and fill the translated column." _n
        file write `_mf' "inputcorrection = 1 applies everything found there on the next run." _n _n
        file write `_mf' "Only rows not previously sent are exported. Set oe_export_all = 1 to send" _n
        file write `_mf' "everything again." _n _n
        file write `_mf' "You can leave the SurveyCTO form open in Excel while running; labeling is" _n
        file write `_mf' "unaffected." _n _n
        file write `_mf' "## What the processing file does, in order" _n _n
        file write `_mf' "For each dataset, in its own block:" _n _n
        file write `_mf' "1. **Label** — 01_Labeling.do applies CAPI value labels and leaves the" _n
        file write `_mf' "   dataset in memory. No _LABELED_ file is written." _n
        file write `_mf' "2. **Apply translations** — anything returned in 05_Translation/02_Translated/" _n
        file write `_mf' "   is injected BEFORE your cleaning runs, so your rules see translated text." _n
        file write `_mf' "3. **Core variables** — mdf_core_vars derives fielddate from starttime" _n
        file write `_mf' "   and total_duration from duration, when the import did not supply them." _n
        file write `_mf' "4. **Your cleaning** — SECTION A (field fixes that must reach today's HFC)" _n
        file write `_mf' "   then SECTION B (final recodes). Both always run, every day." _n
        file write `_mf' "5. **Save** — the cleaned dataset, dated, into the run folder." _n _n
        file write `_mf' "Then once, after all datasets:" _n _n
        file write `_mf' "6. **Merge** — mdf_finalise merge, if merge_required = 1." _n
        file write `_mf' "7. **Export open-ended** — only if exportopenended = 1. It runs after" _n
        file write `_mf' "   cleaning so a translator receives cleaned rows, not raw ones." _n
        file write `_mf' "8. **Publish** — mdf_finalise publish copies each cleaned dataset to" _n
        file write `_mf' "   07_Cleaned Dataset/ under a stable, undated name." _n _n
        file write `_mf' "Defaults when you launch the processing file on its own: labeling and applying" _n
        file write `_mf' "translations are ON, exporting is OFF. Producing cleaned data never sends" _n
        file write `_mf' "files to a translator as a side effect." _n _n
        file write `_mf' "## Configuration reference" _n
        file write `_mf' "" _n
        file write `_mf' "Every setting lives in SECTION 0 of the Master DO file. The ones whose" _n
        file write `_mf' "meaning is not obvious from the line itself:" _n
        file write `_mf' "" _n
        file write `_mf' "| Setting | Accepted values |" _n
        file write `_mf' "|---|---|" _n
        file write `_mf' "| capi_override | leave empty to auto-detect the most recent .xlsx in 01_Survey_Instruments/02_CAPI/, or name one form |" _n
        file write `_mf' "| capi_language | the ODKSplit label language, e.g. English |" _n
        file write `_mf' "| capi_verbose | 1 prints the ODKSplit variable list, 0 labels silently |" _n
        file write `_mf' "| oe_export_all | 0 exports only rows never sent before, 1 re-exports everything |" _n
        file write `_mf' "| audio_drop_before | leave empty to drop interviews before yesterday, or give a fixed YYYYMMDD |" _n
        file write `_mf' "| audio_keep_enums | leave empty to sample every enumerator, or give space-separated numeric enum IDs, e.g. 1 2 5 |" _n
        file write `_mf' "| audio_seed | fixes the sample so the same run reproduces the same draw |" _n
        file write `_mf' "| merge_datasets | space-separated dataset indices, e.g. 1 3 |" _n
        file write `_mf' "| import_fingerprint | 1 re-imports only when the raw export actually changed |" _n
        file write `_mf' "| hfc_excel_aliases, hfc_dta_aliases | extra global names pointing at the report and the target dataset, so existing team code keeps working |" _n
        file write `_mf' "| verbose | 1 runs each stage so Stata's errors print, 0 runs them silently |" _n
        file write `_mf' "" _n
        file write `_mf' "The variable lists (meta_front, meta_ids, tail, timer_start, timer_end) name" _n
        file write `_mf' "the columns the checks treat as identifiers, front matter and trailing" _n
        file write `_mf' "metadata. With more than one dataset, use the numbered forms: meta_front_1," _n
        file write `_mf' "meta_ids_1 and so on, one set per dataset." _n
        file write `_mf' "" _n
        file write `_mf' "## Dataset naming" _n
        file write `_mf' "" _n
        file write `_mf' "A dataset takes its name from the import DO file. SurveyCTO appends _wide to" _n
        file write `_mf' "the export of a form containing repeat groups; Master strips that suffix, so" _n
        file write `_mf' "form_one_wide becomes the dataset form_one. Files written into a run folder" _n
        file write `_mf' "carry the stage and the date, for example form_one_CLEANED_20260824.dta." _n
        file write `_mf' "" _n
        file write `_mf' "## Missing core variables" _n
        file write `_mf' "" _n
        file write `_mf' "The checks need key, enum, fielddate and duration. When an import does not" _n
        file write `_mf' "supply fielddate or total_duration, mdf_core_vars derives them from" _n
        file write `_mf' "starttime and duration. If a variable cannot be derived at all, the checks" _n
        file write `_mf' "that need it are skipped with a message rather than failing the run." _n
        file write `_mf' "" _n
        file write `_mf' "## Where the explanations live" _n _n
        file write `_mf' "The generated DO files carry headings, not essays. Why the framework is" _n
        file write `_mf' "shaped this way is recorded once, in Instruction/DECISIONS.md, as a set of" _n
        file write `_mf' "numbered decisions. The code itself stays free of them." _n _n
        file write `_mf' "## If a run fails" _n _n
        file write `_mf' "The run stops and prints the stage that failed, Stata's own error message," _n
        file write `_mf' "the file it happened in, and the log path. Read the last screen first." _n _n
        file write `_mf' "## Reproducing a past run" _n _n
        file write `_mf' "Each 03_HFC/NN_..._HFC_YYYYMMDD/ folder holds the dated dataset snapshot the" _n
        file write `_mf' "report for that date was computed from. 07_Cleaned Dataset/ always holds the" _n
        file write `_mf' "CURRENT data; the dated snapshot is what reproduces history." _n
        file close `_mf'
        di as result _n "README.md written."
    }
    else di as error "WARNING: could not write README.md."

    *  ── CAPI verification ──────────────────────────────────────────────────────
    di as result "CAPI directory initialization: OK"
end
